[package]
name = "untitled"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.13.3"
prost-derive = "0.13.3"
tokio-stream = "0.1.16"
tonic = "0.12"
tokio = { version = "1.41", features = ["full"] }

[build-dependencies]
tonic-build = "0.12"